<?php

/**
 * TOBENTO
 *
 * @copyright   Tobias Strub, TOBENTO
 * @license     MIT License, see LICENSE file distributed with this source code.
 * @author      Tobias Strub
 * @link        https://www.tobento.ch
 */

declare(strict_types=1);

namespace Tobento\App\Block\Field;

use Tobento\App\Block\FieldInterface;
use Tobento\Service\Tag\Attributes;
use Tobento\Service\View\ViewInterface;

/**
 * HtmlTextEditor field
 *
 * Represents a text field edited through a JS‑based rich‑text editor.
 * The user does not edit raw HTML directly; instead, the editor provides
 * formatting tools (bold, italic, lists, links, etc.) and generates HTML
 * as its output.
 *
 * The generated HTML is sanitized before rendering to ensure safe output.
 *
 * This field is intended for blocks that require rich text content
 * produced via a JS editor, not manual HTML editing.
 */
class HtmlTextEditor implements FieldInterface
{
    /**
     * Create a new HtmlTextEditor instance.
     *
     * @param string $html The HTML generated by the JS editor.
     * @param string $field The field name (e.g. "answer", "translation").
     * @param bool $translatable Whether the field is translatable
     * @param int|null $itemIndex Optional item index for items-based blocks.
     * @param array $toolbar The toolbar configuration for the JS editor.
     *    If empty, all editor tools are enabled.
     * @param ViewInterface $view The view service used for sanitization.
     */
    public function __construct(
        protected string $html,
        protected string $field,
        protected bool $translatable,
        protected null|int $itemIndex,
        protected array $toolbar,
        protected ViewInterface $view,
    ) {}

    /**
     * Sets or overrides the toolbar configuration for the editor.
     *
     * @param array $toolbar The toolbar configuration (e.g. ["bold", "italic", "link"]).
     * @return static
     */
    public function withToolbar(array $toolbar): static
    {
        $this->toolbar = $toolbar;
        return $this;
    }
    
    /**
     * Render the field output.
     *
     * @return string Sanitized HTML safe for frontend rendering.
     * @psalm-suppress UndefinedInterfaceMethod View macros
     */
    public function render(): string
    {
        return $this->view->sanitizeHtml($this->html);
    }

    /**
     * Render the field for editing in the CRUD layer.
     *
     * @return string HTML containing the JS editor wrapper.
     */
    public function renderEditable(): string
    {
        $attributes = empty($this->toolbar)
            ? new Attributes(['data-editor' => ''])
            : new Attributes(['data-editor' => ['toolbar' => $this->toolbar]]);

        $attributes->set('data-editor-field', $this->field);
        $attributes->set('data-editor-translatable', $this->translatable ? '1' : '0');
        
        // Only for items blocks
        if ($this->itemIndex !== null) {
            $attributes->set('data-editor-item', (string)$this->itemIndex);
        }
        
        return sprintf('<div%s>', (string)$attributes).$this->render().'</div>';
    }
    
    /**
     * Returns the raw underlying value.
     *
     * @return mixed
     */
    public function value(): mixed
    {
        return $this->html;
    }
}